### ISSUE TITLE
Add TimeShift to npm

### ISSUE THREAD

**Issue by badabam** [plaa/TimeShift-js#6]
I would love to use TimeShift as a node module. Unfortunately it is not registered at npm. Please consider doing that.

**Comment by johanbove** [comment]
:+1:

**Comment by plaa** [comment]
Grrr..  I tried to publish it, but npm adduser wouldn't work, failed mysteriously with the server replying with 400 whatever I tried.  Wondered if the problem was the old npm version on Linux Mint so I tried upgrading, and now npm is totally borked.  Will have to try to sort it out some other day, sorry.

**Comment by badabam** [comment]
It might not be related, but I don't see a package.json file in your project. Don't you need that for registering?

**Comment by plaa** [comment]
I haven't yet committed the package.json. The adduser command shouldn't require it anyway.

**Comment by plaa** [comment]
Just got it published, sorry for the delay.  https://www.npmjs.com/package/timeshift-js
